// <auto-generated />
namespace SuperScheduler.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddPositionListToOneWeekSchedule : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddPositionListToOneWeekSchedule));
        
        string IMigrationMetadata.Id
        {
            get { return "201805162151379_AddPositionListToOneWeekSchedule"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
